import type { Metadata } from "next";
import "./globals.css";
import Providers from './Providers'

// Remove or comment out the font imports if you don't have these files
// const geistSans = localFont({...})
// const geistMono = localFont({...})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
